### ISSUE TITLE
Navbar: Improve spacing in navbar buttons

### ISSUE THREAD

**Issue by victor-accarini** [profusion/pf-website#17]
The usability of the navbar can be improved a little, especially the buttons, they should have a broader clickable area.

Here is a few improvements that can be made.

![image](https://user-images.githubusercontent.com/5943663/115296300-2e77ba80-a131-11eb-9e26-49b72cc6d7d6.png)
![image (1)](https://user-images.githubusercontent.com/5943663/115296302-2fa8e780-a131-11eb-971a-75bef136a500.png)
![image (2)](https://user-images.githubusercontent.com/5943663/115296306-2fa8e780-a131-11eb-94d2-8677d74cbd94.png)

**Comment by GabrielBFurlani** [comment]
Finish!

![image](https://user-images.githubusercontent.com/77974533/115440269-f0889e00-a1e5-11eb-9aaf-73497d47b404.png)
