### ISSUE TITLE
Create Home section content

### ISSUE THREAD

**Issue by victor-accarini** [profusion/pf-website#3]
Add Home content according to design [file](https://drive.google.com/drive/u/1/folders/0B7Ru2BOikqF2cDgtRTRZUy1iT1U).

**Comment by GabrielBFurlani** [comment]
![image](https://user-images.githubusercontent.com/77974533/115441389-2d08c980-a1e7-11eb-96a3-8ff8f2787709.png)

![image](https://user-images.githubusercontent.com/77974533/115441422-37c35e80-a1e7-11eb-8bd0-9ad8fd341a68.png)
